name: bratan
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=51_gnu
  - bzip2=1.0.8=h998d150_6
  - ca-certificates=2025.12.2=hd43f75c_0
  - expat=2.7.3=h5b11e9f_4
  - ld_impl_linux-aarch64=2.44=h4e4ac68_2
  - libexpat=2.7.3=h5b11e9f_4
  - libffi=3.4.4=h419075a_1
  - libgcc=15.2.0=hc18542e_7
  - libgcc-ng=15.2.0=h51576c1_7
  - libgomp=15.2.0=hf47c802_7
  - libnsl=2.0.0=h998d150_0
  - libstdcxx=15.2.0=h9538471_7
  - libstdcxx-ng=15.2.0=h719ae8e_7
  - libuuid=1.41.5=h998d150_0
  - libxcb=1.17.0=hf66535e_0
  - libzlib=1.3.1=h998d150_0
  - ncurses=6.5=h419075a_0
  - openssl=3.0.18=h8a9c3cf_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=hfd63f10_1
  - python=3.11.14=h81fb49f_0
  - readline=8.3=h886d1d0_0
  - setuptools=80.9.0=py311hd43f75c_0
  - sqlite=3.51.0=hc5b20ee_0
  - tk=8.6.15=h987d8db_0
  - wheel=0.45.1=py311hd43f75c_0
  - xorg-libx11=1.8.12=hf66535e_1
  - xorg-libxau=1.0.12=hf66535e_0
  - xorg-libxdmcp=1.1.5=hf66535e_0
  - xorg-xorgproto=2024.1=h998d150_1
  - xz=5.6.4=h998d150_1
  - zlib=1.3.1=h998d150_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - anyio==4.12.0
      - attrs==25.4.0
      - beautifulsoup4==4.14.3
      - bitsandbytes==0.49.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.1.8
      - coloredlogs==15.0.1
      - cuda-bindings==13.0.3
      - cuda-pathfinder==1.2.2
      - datasets==4.4.2
      - dill==0.4.0
      - discord==2.3.2
      - discord-py==2.6.4
      - einops==0.8.1
      - filelock==3.20.0
      - flash==1.0.3
      - flash-attn==2.8.3
      - flatbuffers==25.12.19
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gdown==5.2.0
      - grpcio==1.76.0
      - gtts==2.5.4
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - idna==3.11
      - jinja2==3.1.6
      - markdown==3.10
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - networkx==3.6.1
      - ninja==1.13.0
      - numpy==2.3.5
      - nvidia-cublas==13.1.0.3
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti==13.0.85
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc==13.0.88
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime==13.0.48
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cudnn-cu13==9.15.1.9
      - nvidia-cufft==12.0.0.61
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile==1.15.1.6
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand==10.4.0.35
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver==12.0.4.66
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse==12.6.3.3
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-cusparselt-cu13==0.8.0
      - nvidia-nccl-cu12==2.28.9
      - nvidia-nccl-cu13==2.28.9
      - nvidia-nvjitlink==13.0.88
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.4.5
      - nvidia-nvshmem-cu13==3.4.5
      - nvidia-nvtx==13.0.85
      - nvidia-nvtx-cu12==12.8.90
      - onnxruntime==1.23.2
      - packaging==25.0
      - pandas==2.3.3
      - peft==0.18.0
      - pillow==12.0.0
      - piper-tts==1.3.0
      - propcache==0.4.1
      - protobuf==6.33.2
      - psutil==7.1.3
      - pyarrow==22.0.0
      - pycparser==2.23
      - pynacl==1.6.1
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.7.0
      - sentencepiece==0.2.1
      - six==1.17.0
      - soupsieve==2.8.1
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tokenizers==0.22.1
      - torch==2.11.0.dev20251226+cu130
      - torchaudio==2.10.0.dev20251226+cu130
      - torchvision==0.25.0.dev20251226+cu130
      - tqdm==4.67.1
      - transformers==4.57.3
      - triton==3.6.0+git9844da95
      - trl==0.26.2
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - urllib3==2.6.2
      - werkzeug==3.1.4
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /home/yaljnadi/anaconda3/envs/bratan
